const data = [
  {
    title: "Instanțe CPU Dedicat-Intel",
    pricingCards: [
      {
        cpu: "4",
        ram: "16 GB",
        storage: "100 GB",
        storageType: "NVMe HA",
        transfer: "10 TB",
        price: "10 EUR",
      },
      {
        cpu: "6",
        ram: "24 GB",
        storage: "150 GB",
        storageType: "NVMe HA",
        transfer: "10 TB",
        price: "15 EUR",
      },
      {
        cpu: "8",
        ram: "32 GB",
        storage: "200 GB",
        storageType: "NVMe HA",
        transfer: "10 TB",
        price: "20 EUR",
      },
      {
        cpu: "12",
        ram: "48 GB",
        storage: "300 GB",
        storageType: "NVMe HA",
        transfer: "10 TB",
        price: "30 EUR",
      },
      {
        cpu: "16",
        ram: "64 GB",
        storage: "400 GB",
        storageType: "NVMe HA",
        transfer: "10 TB",
        price: "40 EUR",
      },
      {
        cpu: "24",
        ram: "96 GB",
        storage: "600 GB",
        storageType: "NVMe HA",
        transfer: "10 TB",
        price: "60 EUR",
      },
      {
        cpu: "32",
        ram: "128 GB",
        storage: "800 GB",
        storageType: "NVMe HA",
        transfer: "10 TB",
        price: "80 EUR",
      },
      {
        cpu: "64",
        ram: "256 GB",
        storage: "1.6 TB",
        storageType: "NVMe HA",
        transfer: "10 TB",
        price: "100 EUR",
      },
    ],
  },
  {
    title: "Instanțe Shared-Intel",
    pricingCards: [
      {
        cpu: "1",
        ram: "2 GB",
        storage: "20 GB",
        storageType: "NVMe HA",
        transfer: "10 TB",
        price: "4 EUR",
      },
      {
        cpu: "2",
        ram: "4 GB",
        storage: "40 GB",
        storageType: "NVMe HA",
        transfer: "10 TB",
        price: "6 EUR",
      },
      {
        cpu: "4",
        ram: "8 GB",
        storage: "80 GB",
        storageType: "NVMe HA",
        transfer: "10 TB",
        price: "8 EUR",
      },
    ],
  },
  {
    title: "Instanțe Shared-AMD",
    pricingCards: [
      {
        cpu: "1",
        ram: "3 GB",
        storage: "25 GB",
        storageType: "NVMe HA",
        transfer: "10 TB",
        price: "5 EUR",
      },
      {
        cpu: "2",
        ram: "6 GB",
        storage: "50 GB",
        storageType: "NVMe HA",
        transfer: "10 TB",
        price: "7 EUR",
      },
      {
        cpu: "4",
        ram: "12 GB",
        storage: "90 GB",
        storageType: "NVMe HA",
        transfer: "10 TB",
        price: "9 EUR",
      },
    ],
  },
];

export default data;
